# Generated by Django 6.0.2 on 2026-02-26 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(default='', verbose_name='Descrição do Problema')),
                ('solucao', models.TextField(blank=True, null=True, verbose_name='Solução')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meio_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartão de Crédito/Débito'), ('boleto', 'Boleto')], default='pix', max_length=50)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Inteligente.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
