# Generated by Django 6.0.2 on 2026-02-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Inteligente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
