# Generated by Django 6.0.2 on 2026-02-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Inteligente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
