# Generated by Django 6.0.2 on 2026-02-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Inteligente', '0002_chamado_ultima_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
