# Generated by Django 6.0.2 on 2026-02-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Inteligente', '0002_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='meio_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartão de Crédito/Débito'), ('boleto', 'Boleto')], default='pix', max_length=50),
        ),
        migrations.AddField(
            model_name='chamado',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
